# -*- mode: ruby -*-
# vi: set ft=ruby :
#

# This file is just the entrypoint that loads more ruby-code to execute the vagrant configuration
current_working_dir = File.dirname(File.expand_path(__FILE__))
vagrant_ffb_dirname = ".ffb"

require 'net/http'
require 'optparse'
ffb_tools_file = File.dirname(File.expand_path(__FILE__)) + "/#{vagrant_ffb_dirname}/ffb.tools.rb"
if File.file?(ffb_tools_file)
  require ffb_tools_file
end

vagrant_ffb_path = "#{current_working_dir}/#{vagrant_ffb_dirname}/"
vagrant_environment_separator = "_"
vagrant_main_script_filename = "ffb.vagrant.rb"
vagrant_environment = nil

module VAGRANT_ENVIRONMENT
  PRODUCTION  = "prod"
  DEVELOPMENT = "dev"
  LOCAL       = "local"
end

vagrant_environment = "prod"

# overwrite default vagrant environment if parameter given
OptionParser.new do |opts|
  opts.on("-e", "--env [V_ENV]", String, "Set Vagrant Environment") do |current_env|
    case current_env
    when VAGRANT_ENVIRONMENT::PRODUCTION
      vagrant_environment = current_env
    when VAGRANT_ENVIRONMENT::LOCAL
      vagrant_environment = current_env
    when VAGRANT_ENVIRONMENT::DEVELOPMENT
      vagrant_environment = current_env
    else
      # do nothing and keep prod
    end
  end
end.parse!

remote_gist_base_uri = "https://gist.githubusercontent.com/tfr-ffb/7e1ac6dcdc7d168e63ecb87601a75821/raw/"
filename_mapping = [
    { remote: vagrant_main_script_filename, local: vagrant_main_script_filename },
    { remote: "ansible.cfg", local: "ansible.cfg" },
    { remote: "hint.txt", local: "hint.txt" },
    { remote: "vagrant-default-config.yml", local: "vagrant-default-config.yml" },
    { remote: "ffb.tools.rb", local: "ffb.tools.rb" }
]

if File.file?(ffb_tools_file)
  Tools::Logger.log(Tools::Logger::LOG_LEVEL::INFO,"Detected Vagrant Environment: #{Tools::Logger::LOG_COLOR::ERROR}#{vagrant_environment}#{Tools::Logger::LOG_COLOR::RESET}")
end

# create .ffb directory if not existing
unless File.file?(vagrant_ffb_path); FileUtils::mkdir_p(vagrant_ffb_path); end

# sometimes we want to modify local files and keep the changes for testing purposes
# thats what the local environment is built in for, unless the environment is local, all files will be redownloaded
unless vagrant_environment == VAGRANT_ENVIRONMENT::LOCAL
#download the correct files from gist
  filename_mapping.each do |filename|
    # build local and remote uri
    remote_uri = "#{remote_gist_base_uri}#{filename[:remote]}#{vagrant_environment_separator}#{vagrant_environment}"
    local_uri = "#{vagrant_ffb_path}#{filename[:local]}"
    begin
      File.write(local_uri, Net::HTTP.get(URI.parse(remote_uri)))
    rescue
      if !File.file?(local_uri)
        # without the file we cannot continue
        raise "Could not find #{local_uri} and could not download default Vagrantfile from #{remote_uri}, please check your internet connection to proceed."
      else
        # the file is there, so we just output an information
        if File.file?(ffb_tools_file)
           Tools::Logger.log(Tools::Logger::LOG_LEVEL::INFO,"Could not download from #{remote_uri}, please check your internet connection.")
        end
      end
    end
  end
end

# execute the ffb vagrant library
load "#{vagrant_ffb_path}#{vagrant_main_script_filename}"
FfbVagrant::run