---
apache_remove_default_vhost: true

apache_create_vhosts: true
apache_vhosts_filename: "vhosts.conf"
apache_vhosts_template: "vhosts.conf.j2"

apache_listen_ip: "*"
apache_listen_port: 80

d_root: "/var/www/vhosts/sulo"

apache_vhosts:
  - servername: "{{ ansible_fqdn }}"
    srveradmin: "admin@localhost"
    documentroot: "{{ d_root }}"
    extra_parameters: |
                  ProxyPassMatch ^/(.*\.php(/.*)?)$ "unix:/run/php/php{{ php_version }}-fpm.sock|fcgi://localhost{{ d_root }}"

apache_allow_override: "All"
apache_options: "+Indexes +FollowSymLinks"

apache_mods_enabled:
  - rewrite.load
  - autoindex.load
  - expires.load
  - headers.load