---
- name: Install Sulu
  hosts: all
  become: true
  pre_tasks:
    - name: load all vars
      include_vars:
        dir: 'vars'
  roles:
    - fourforbusiness.basic-setup
    - geerlingguy.nodejs
    - fourforbusiness.dev-lamp
    - geerlingguy.composer
    - fourforbusiness.mysql-prepare-db
